"""Tests for aph.config — Constants and configuration."""

import pytest
from pathlib import Path

from aph.config import (
    AGENT_DIR_NAME,
    BUNDLED_SKILLS_DIR,
    CORE_SKILLS,
    INIT_SUBDIRS,
    MANIFEST_FILE,
    PACKAGE_ROOT,
    SKILLS_REGISTRY_FILE,
    SKILLS_SUBDIR,
)


class TestPackagePaths:
    """Verify that package paths resolve correctly."""

    def test_package_root_exists(self):
        """PACKAGE_ROOT should point to the repo root."""
        assert PACKAGE_ROOT.exists()
        assert (PACKAGE_ROOT / "pyproject.toml").exists()

    def test_bundled_skills_dir_exists(self):
        """Bundled .agent/skills/ must exist for the CLI to work."""
        assert BUNDLED_SKILLS_DIR.exists()
        assert BUNDLED_SKILLS_DIR.is_dir()

    def test_skills_registry_file_exists(self):
        """skills_registry.json must exist (generated by generate_registry.py)."""
        assert SKILLS_REGISTRY_FILE.exists()


class TestCoreSkills:
    """Verify core skills configuration."""

    def test_core_skills_is_nonempty_list(self):
        """Core skills must be a non-empty list."""
        assert isinstance(CORE_SKILLS, list)
        assert len(CORE_SKILLS) > 0

    def test_core_skills_are_strings(self):
        """Each core skill must be a string."""
        for skill in CORE_SKILLS:
            assert isinstance(skill, str)

    def test_core_skills_exist_in_bundled_dir(self):
        """Every core skill must have a corresponding directory in .agent/skills/."""
        for skill in CORE_SKILLS:
            skill_dir = BUNDLED_SKILLS_DIR / skill
            assert skill_dir.exists(), f"Core skill '{skill}' not found at {skill_dir}"
            skill_md = skill_dir / "SKILL.md"
            assert skill_md.exists(), f"Core skill '{skill}' missing SKILL.md"

    def test_expected_core_skills(self):
        """Core skills should include the planned defaults."""
        expected = {
            "brainstorming",
            "git-pushing",
            "expert-skill-creator",
            "clean-code",
            "systematic-debugging",
            "verification-before-completion",
            "test-driven-development",
        }
        assert set(CORE_SKILLS) == expected


class TestConstants:
    """Verify constant values are correct."""

    def test_agent_dir_name(self):
        assert AGENT_DIR_NAME == ".agent"

    def test_skills_subdir(self):
        assert SKILLS_SUBDIR == "skills"

    def test_manifest_file(self):
        assert MANIFEST_FILE == ".aph-manifest.json"

    def test_init_subdirs_contain_required(self):
        """Init should create all required subdirectories."""
        required = {"skills", "knowledge", "methodology", "debug", "sources"}
        assert required.issubset(set(INIT_SUBDIRS))
